### ISSUE TITLE
IDL attribute name issue.

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-api#383] opened 2020-02-22 01:26 UTC
The RdfTriple IDL block is not rendering properly, and therefore not linked up properly.   It appears to be an issue with an attribute named "object".  Or for that matter, renaming it to any [short type name](https://heycam.github.io/webidl/#idl-types) like "symbol", "double", etc will not work.  I'm unsure if that's a restriction of WebIDL itself or the respec magic or what.

As an aside, does anyone know an IDL expert that could check the whole [API section](https://www.w3.org/TR/json-ld-api/#the-application-programming-interface)?  I imagine there are best practices or other improvements to be made there.

**Comment by gkellogg** [comment] 2020-02-22 01:41
They keep changing ReSpec, which causes new errors to crop up. There are several reported errors due to `JsonLdInput` including a dictionary, which it doesn't like, but I just gave up on that.

I hadn't seen the `RdfTriple` issue but it probably relates to the relatively new "error when calling a function" issue.

I've changed it to "obj", which isn't ideal, but it's only referenced in one place and it makes the error go away.

**Comment by gkellogg** [comment] 2020-02-22 19:43
See https://github.com/w3c/respec/issues/2767.

**Comment by saschanaz** [comment] 2020-02-23 03:54
> There are several reported errors due to `JsonLdInput` including a dictionary, which it doesn't like, but I just gave up on that.

```webidl
dictionary JsonLdDictionary {};

typedef (JsonLdDictionary or USVString or sequence<(JsonLdDictionary or USVString)>) JsonLdContext;
```

`JsonLdContext` indeed includes a dictionary. [The spec says](https://heycam.github.io/webidl/#idl-operations):

> If the type of an argument is a dictionary type or a union type that has a dictionary type as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument must be specified as optional and have a default value provided.

And thus the errors. If any of the errors look invalid, please ping me and I'll take a look.

**Comment by gkellogg** [comment] 2020-02-23 21:45
Given WebIDL's limitations, these are not WebIDL errors per-se. However, JSON-LD legitimately uses a dictionary to describe its input, as that's basically what a JSON Object is. The inability to use things based on dictionaries as parameters limits the ability of WebIDL to work with JSON-LD data parameters, and I think is short-sighted.

**Comment by saschanaz** [comment] 2020-02-24 03:47
As I said `_object` is a valid workaround, as a conformant parser will get it as `object`.

**Comment by saschanaz** [comment] 2020-02-24 03:50
Maybe you can use `object` instead? @bzbarsky might know more than me, so pinging.

**Comment by bzbarsky** [comment] 2020-02-24 05:34
I don't think dictionaries have anything to do with the original issue here.

That issue there is a pure grammar one.  `"object"` is the name of an IDL type and hence is not a valid identifier.  The name of a dictionary member is an identifier.  You can list the name as `_object` in the IDL to create an identifier with the string "object", or the IDL spec could change the production for dictionary member names to include non-identifier strings of various sorts (e.g. see what interface members look like, in the https://heycam.github.io/webidl/#index-prod-AttributeName production, which of course also does not allow `object` as a name at the moment...

For the `JsonLdContext` bit, there are a few issues.  Right now the spec at https://w3c.github.io/json-ld-api/#dom-jsonldprocessor has:
```
optional JsonLdContext context = null
```
in a few places which is not valid IDL, but using `= {}` instead of `= null` would be valid.  That said, I don't understand the `JsonLdContext` use of a dictionary.  Unwinding it, we get to `JsonLdDictionary`, which is defined as an empty dictionary.  If the idea is that the set of key names is not known ahead of time, then a dictionary is not the right type; the right type for that is `record`.  See <https://heycam.github.io/webidl/#idl-record>.  Certainly the description at https://w3c.github.io/json-ld-api/#dom-jsonlddictionary sounds a lot more like a `record<DOMString, any>` (or USVString for the key type if that's an expected restriction?) than a dictionary....

**Comment by bzbarsky** [comment] 2020-02-24 05:36
And to be clear, if we change the grammar we would have to audit carefully to make sure that allowing `object` there does not make the grammar ambiguous.  Doable, but takes some work and may turn out to fail if the grammar _does_ become ambiguous.

**Comment by gkellogg** [comment] 2020-02-24 06:12
> That issue there is a pure grammar one. `"object"` is the name of an IDL type and hence is not a valid identifier. You can list the name as `_object` in the IDL to create an identifier with the string "object", or the IDL spec could change the production for interface attribute names to include this string in https://heycam.github.io/webidl/#index-prod-AttributeNameKeyword.

Okay, that may work okay for us then. Thanks.

> For the `JsonLdContext` bit, there are a few issues. Right now the spec at https://w3c.github.io/json-ld-api/#dom-jsonldprocessor has:
> 
> ```
> optional JsonLdContext context = null
> ```
> 
> in a few places which is not valid IDL, but using `= {}` instead of `= null` would be valid. That said, I don't understand the `JsonLdContext` use of a dictionary. Unwinding it, we get to `JsonLdDictionary`, which is defined as an empty dictionary. If the idea is that the set of key names is not known ahead of time, then a dictionary is not the right type; the right type for that is `record`. See https://heycam.github.io/webidl/#idl-record. Certainly the description at https://w3c.github.io/json-ld-api/#dom-jsonlddictionary sounds a lot more like a `record<DOMString, any>` (or USVString for the key type if that's an expected restriction?) than a dictionary....

We can experiment with _record_ to see if that will do it. Internally, a JSON object is parsed into a `map` which seemed closest to an IDL `dictionary`, but perhaps `record` will work better.

It is indeed the case that a JSON-LD document, including a context, has an unknown, and possibly empty (rarely) set of entries. For the API, it is typically a string resaving to a URL, an array of objects, or an object. But, as you say, that is a different unrelated issue.

**Comment by bzbarsky** [comment] 2020-02-24 06:39
`dictionary` and `record` are both maps.  A `dictionary` is a map which contains keys that come from a known fixed subset (think "set of keys determined at browser compile time", if that helps to make it concrete) and values of various types.  A `record` is a map which contains an arbitrary set of keys (the actual set of keys ends up being determined at runtime), all with the same type of value (but that type can be `any`, with further processing done in prose based on key names, etc).

Some specs take `object` and then in prose both convert it to a `dictionary` to extract some specific set of keys/values they care about and to a `record` to grab the rest of the keys/values.  Web Animations does something like that.

Concretely, I took a look at what the `input` parameter is used for in https://w3c.github.io/json-ld-api/ and I can't quite make sense of how it's expected to work.  The spec seems to be assuming that it gets something completely built up infra types, but there is no generic algorithm for converting a random JS object to a infra-types-only thing that I am aware of.  This spec probably needs to define the processing model it wants there...

(I am also a bit confused about some of the async work that at first glance looks like it would involve side-effects and hence needs to be explicitly synchronized with the event loop and isn't, but maybe I am misunderstanding the setup.)

**Comment by gkellogg** [comment] 2020-02-24 16:17
> `dictionary` and `record` are both maps. A `dictionary` is a map which contains keys that come from a known fixed subset (think "set of keys determined at browser compile time", if that helps to make it concrete) and values of various types. A `record` is a map which contains an arbitrary set of keys (the actual set of keys ends up being determined at runtime), all with the same type of value (but that type can be `any`, with further processing done in prose based on key names, etc).

`record`  matches our model best.

> Concretely, I took a look at what the `input` parameter is used for in https://w3c.github.io/json-ld-api/ and I can't quite make sense of how it's expected to work. The spec seems to be assuming that it gets something completely built up infra types, but there is no generic algorithm for converting a random JS object to a infra-types-only thing that I am aware of. This spec probably needs to define the processing model it wants there...

A string is interpreted as a URL to something that results in JSON (possibly through HTML). JSON is transformed to the _internal representation_, which has some discussion, where JSON primitives are described using the closest analogs from infra using `array`, `map`, `number`, `Boolean` and `null`. The array and dictionary/record alternatives are a concession for processors operating on the _internal representation_ directly. Perhaps this needed to be expanded upon.

> (I am also a bit confused about some of the async work that at first glance looks like it would involve side-effects and hence needs to be explicitly synchronized with the event loop and isn't, but maybe I am misunderstanding the setup.)

There may be some side effect behavior that emerged recently which was not adequately treated, but mostly the API methods are intended to work synchronously within the promis, although some internal I/O is not explicitly described. Most methods involve resolving a promise to expand the input, and there could be some bleed-through of information retrieved from this internal call which could be reconsidered. 

Note that the IDL is intended to express expected behavior, and implementations are not bound to this, although the JavaScript version would closely adhere to it.

Thanks for looking, and any other points of advice are greatly appreciated, as our group is lacking in deep experience with WebIDL, particularly as it has evolved over time.

**Comment by bzbarsky** [comment] 2020-02-24 17:35
> The array and dictionary/record alternatives are a concession for processors operating on the internal representation directly.

I mean, in the dictionary/record alternative a JS object is passed in.  Then some combination of IDL and prose needs to define what happens.

> and implementations are not bound to this

Then I'm not sure what the point of the IDL is, if it's not normative...

**Closed** 2020-02-27 18:22 UTC
