### ISSUE TITLE
Processing terms starting with :

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-api#189] opened 2019-10-31 17:04 UTC
What should a processor do with a term that starts with `:` ?

@kasei and my reading is that, with an `@vocab` definition, it should create a term by concatenation.

For example:
```
{"@context": {"@vocab": "http://schema.org/"},
 "@id": "foo:bar-id",
 "@type": "foo:bar-type",
 "foo:bar": "is an absolute iri property",
 "term": "is schema.org/term",
 ":fish": "is schema.org/:fish"
}
```

In the playground the term is ignored completely:
  http://tinyurl.com/yxk2vka2

In Gregg's distiller it generates the `schema.org/:fish` property.

The text in https://www.w3.org/TR/json-ld11-api/#algorithm-4 step 6 says "contains a colon", which it does, and then to split it. This would in theory generate a prefix of empty string and a term of 'fish'. As there isn't an expansion possible, it seems like the playground drops it.

We think that step 6 should be modified to say that it contains a colon, **as the second or subsequent character**. This would make Gregg's implementation correct, and the vocab would used.

There should also be a test for this (admittedly pathological) case.

**Comment by gkellogg** [comment] 2019-10-31 22:30
Perhaps: "contains a colon anywhere after the first character."

Other potential terms are:

* `:foo:`
* `:foo`
* `foo:`

Note that we specifically handle a term `foo:` in 17.5 of Create Term Definition. We should also update step 18.

**Comment by azaroth42** [comment] 2019-10-31 22:41
What would we expect `:foo:` to do? Given that the first character is `:`, I would think this is also just a term, and thus would be concatenated with the vocabulary to form an IRI. But it would still match the "contains a colon after the first character" test. 

Perhaps it's a special case for the first or last character being a colon?

**Comment by gkellogg** [comment] 2019-10-31 23:42
It would be treated much like `foo:`, meaning that constructing a compact IRI would not add a new `:` between prefix and suffix, and expanding it would  not remove that trailing colon, so that the term with the training colon would be retained. In this case, it would also begin with a colon.

IIRC, the trainling-colon term was added to ensure that it could be used, and was intended to be used as a prefix. No good reason to create a term with a leading colon, but we should handle it one way or the other.

**Comment by iherman** [comment] 2019-11-10 05:40
Agree with closing.

**Closed** 2019-11-11 19:27 UTC
Labels: propose closing
